### ISSUE TITLE
compose_geoip-updater keep restarting

### ISSUE THREAD

**Issue by chacuavip10** [crazy-max/docker-rtorrent-rutorrent#100]
Hi, i'm quite new to github but i will try my best.
i follow the guide in the readme, with docker-compose.
- compose_rtorrent-logs start normally
- compose_rtorrent-rutorrent start normally, and state healthy
- compose_geoip-updater alway restart after few seconds, but in the data folder it already download the db (2 file mmdb) and the plugin in main rutorrent show correct location for public ip.
Is this like normal behaviour or maybe something is wrong?
A few log in docker-compose logs -f:
```

Traceback (most recent call last):
  File "docker/api/client.py", line 214, in _retrieve_server_version
  File "docker/api/daemon.py", line 181, in version
  File "docker/utils/decorators.py", line 46, in inner
  File "docker/api/client.py", line 237, in _get
  File "requests/sessions.py", line 543, in get
  File "requests/sessions.py", line 530, in request
  File "requests/sessions.py", line 643, in send
  File "requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 200, in perform_command
  File "compose/cli/command.py", line 70, in project_from_options
  File "compose/cli/command.py", line 153, in get_project
  File "compose/cli/docker_client.py", line 43, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "docker/api/client.py", line 197, in __init__
  File "docker/api/client.py", line 222, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))
[71311] Failed to execute script docker-compose
```

**Comment by crazy-max** [comment]
@chacuavip10 [`geoip-updater` service](https://github.com/crazy-max/docker-rtorrent-rutorrent/blob/e7900aa843bb6c92510a6a30d3bc10b98b190c8b/examples/compose/docker-compose.yml#L4-L10) is used to update GeoIP dbs of you have a [MaxMind's license key](https://crazymax.dev/geoip-updater/usage/prerequisites/). If you don't you can safely remove this service.
